spring:
    datasource:
      url : jdbc:mysql://localhost:3306/tobispring?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
        username : root
        password : 1234
        driver-class-name : com.mysql.cj.jdbc.Driver

jpa:
show-sql: true
hibernate:
ddl-auto: none
